FROM ubuntu:24.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    make \
    pkg-config \
    libpam0g-dev \
    libldap2-dev \
    liboath-dev \
    vim \
    gdb \
    valgrind \
    ldap-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["/bin/bash"]
